### ISSUE TITLE
Vertical TM edges w/ multiple rules overlap.

### ISSUE THREAD

**Issue by dag10** [bgrawi/jsflap#22]
![image](https://cloud.githubusercontent.com/assets/4248810/11724149/57ff7846-9f40-11e5-8468-bee2d6385193.png)

**Comment by bgrawi** [comment]
Hmm, yeah I see what you mean, this might be hard to figure out the math to align them correctly. Maybe just do what jflap does and make the labels rotated to be parallel to the line, but it might look weird with one-character transitions.
